vscode:
  extensions:
    - Dart-Code.flutter@3.3.0-beta.4:wCqXa/Ih/LTzfyko19agfQ==
    - Dart-Code.dart-code@3.3.0-beta.4:z+hDckQldFt7W9jYHkgiTQ==

tasks:
  - command: npm install -g serve
  - command: chmod -R 777 start.sh && chmod -R 777 create.sh && sh start.sh && gp env PATH="$PATH:/workspace/FlutterUnicampMiniCurso/flutter/bin" && sh create.sh && chmod -R 777 FlutterTwitterClone/build.sh
